# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      # image: continuumio/miniconda3:4.10.3
      image: ghcr.io/openmc-data-storage/miniconda3_4.9.2_endfb-7.1_nndc_tendl_2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependancies
        run: |
          conda install -c conda-forge mamba
          mamba install -c conda-forge openmc

      - name: install package
        run: |
          pip install --upgrade pip
          pip install .
          python -c "import regular_mesh_plotter"

      - name: install packages for tests
        run: |
          pip install .[tests]

      - name: Run test_utils
        run: |
          pytest tests

      - name: Run examples
        run: |
          cd examples
          python plot_minimal_example.py
          python plot_with_custom_color_map.py
