# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: openmc/openmc-dagmc:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          python setup.py install

      - name: install packages for tests
        run: |
          pip install -r requirements-test.txt 

      - name: Run test_utils
        run: |
          cp tests/example.stl .
          pytest tests/ -v --cov=regular_mesh_plotter --cov-append --cov-report term --cov-report xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v2

      - name: Run examples
        run: |
          cd examples
          python create_statepoint_file_with_meshes_openmc_dagmc.py
          python create_statepoint_file_with_meshes_openmc.py
          # python examples_from_readme.py  # commented out as it requires entire neutronics workflow
          python plot_regular_mesh_dose_tally.py
          python plot_regular_mesh_dose_tally_with_geometry.py
          python plot_regular_mesh_tally.py
          python plot_regular_mesh_tally_with_geometry.py
          python plot_regular_mesh_values.py
          python plot_regular_mesh_values_with_geometry.py
